services:
  springboot:
    container_name: spring-dev-app
    image: wegotoo/dev:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev-env
      TZ: "Asia/Seoul"
    networks:
      - app_network

  monogodb:
    container_name: mongodb
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      SPRING_PROFILES_AVTIVE: dev-env
      TZ: "Asia/Seoul"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge