spring:
  profiles:
    active:
      - local-env
    group:
      local-env:
        - local
      dev-env:
        - dev
      prod-env:
        - prod
    include:
      - jwt
      - oauth
      - s3
      - slack