spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:wegotoo
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: wegotoo
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB